/**
 * gen-component-map.ts
 *
 * Regenerates dev-tools/component-map.json: a map of identifier -> source file,
 * used to turn a Vercel Toolbar comment (which points at a rendered element)
 * into the file you actually edit.
 *
 * It scans frontend/src for two kinds of identifier, so a toolbar comment
 * resolves whether the tagged element is a whole component or just a section:
 *   1. `data-component="X"` attribute values  -> the file the markup lives in
 *   2. exported React component names          -> the file they're defined in
 * (1) wins on conflict, since a data-component tag is the exact element a
 * reviewer clicked.
 *
 * Deliberately a simple regex scan (no TS compiler) - it's a solo-maintained
 * internal tool. Run: `npm run map:components`.
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, "..");
const SRC_DIR = join(REPO_ROOT, "frontend", "src");
const OUT = join(HERE, "component-map.json");

const EXTS = new Set([".ts", ".tsx"]);

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    if (name === "node_modules" || name.startsWith(".")) continue;
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) out.push(...walk(full));
    else if (EXTS.has(name.slice(name.lastIndexOf(".")))) out.push(full);
  }
  return out;
}

// posix-style repo-relative path, e.g. "frontend/src/components/RodsRecorder.tsx"
function rel(file: string): string {
  return relative(REPO_ROOT, file).split("\\").join("/");
}

const DATA_COMPONENT = /data-component=["'`]([A-Za-z0-9_-]+)["'`]/g;
// export function Foo | export default function Foo | export const Foo = ... =>|(  | export class Foo
const EXPORTED = [
  /export\s+function\s+([A-Z][A-Za-z0-9_]*)/g,
  /export\s+default\s+function\s+([A-Z][A-Za-z0-9_]*)/g,
  /export\s+const\s+([A-Z][A-Za-z0-9_]*)\s*[:=]/g,
  /export\s+class\s+([A-Z][A-Za-z0-9_]*)/g,
];

function main() {
  const files = walk(SRC_DIR);
  const dataMap: Record<string, string> = {};
  const exportMap: Record<string, string> = {};

  for (const file of files) {
    const text = readFileSync(file, "utf8");
    const r = rel(file);

    for (const m of text.matchAll(DATA_COMPONENT)) {
      // First tag wins; warn on a genuine cross-file duplicate so tags stay unique.
      const key = m[1];
      if (dataMap[key] && dataMap[key] !== r) {
        console.warn(`[map] duplicate data-component "${key}" in ${dataMap[key]} and ${r}`);
      }
      dataMap[key] ??= r;
    }

    for (const re of EXPORTED) {
      for (const m of text.matchAll(re)) {
        exportMap[m[1]] ??= r;
      }
    }
  }

  // data-component values take precedence over exported-name matches.
  const merged: Record<string, string> = { ...exportMap, ...dataMap };
  const sorted = Object.fromEntries(Object.entries(merged).sort(([a], [b]) => a.localeCompare(b)));

  const payload = {
    generated_note: "AUTO-GENERATED by dev-tools/gen-component-map.ts. Do not edit by hand; run `npm run map:components`.",
    source_root: rel(SRC_DIR),
    data_component_count: Object.keys(dataMap).length,
    exported_component_count: Object.keys(exportMap).length,
    map: sorted,
  };
  writeFileSync(OUT, JSON.stringify(payload, null, 2) + "\n");
  console.log(
    `[map] ${Object.keys(sorted).length} identifiers ` +
    `(${Object.keys(dataMap).length} data-component, ${Object.keys(exportMap).length} exported) -> ${rel(OUT)}`,
  );
}

main();
