"""index the columns the worked-hours query scans

Revision ID: a9c2e4f6b8d1
Revises: c5e7a9b1d3f6
Create Date: 2026-07-14

GET /api/hours/worked-history runs on every Profile mount, for every crew member.
It was unbounded (it read every job report ever written); it is now filtered to
the last two weeks. Without these two indexes the filter still forces a full
table scan and only the memory footprint improves, not the read.

  job_reports.updated_at        -> the date window on the job-report side
  off_job_entries.submitted_by_id -> the per-user filter on the off-job side
                                     (also used by GET /api/off-job-hours)

Both tables grow forever, which is the whole reason this endpoint was an OOM
risk on the 512 MB worker (see CLAUDE.md).

Written by hand, not autogenerated: alembic/env.py does not import every model
module, so `alembic revision --autogenerate` emits spurious DROP TABLE ops (see
docs/RUNBOOKS.md, Known defects).
"""
from typing import Sequence, Union

from alembic import op


revision: str = "a9c2e4f6b8d1"
down_revision: Union[str, Sequence[str], None] = "c5e7a9b1d3f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_index(
        "ix_job_reports_updated_at", "job_reports", ["updated_at"], unique=False
    )
    op.create_index(
        "ix_off_job_entries_submitted_by_id",
        "off_job_entries",
        ["submitted_by_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_off_job_entries_submitted_by_id", table_name="off_job_entries")
    op.drop_index("ix_job_reports_updated_at", table_name="job_reports")
