"""initial schema

Revision ID: acb818a08b24
Revises: 
Create Date: 2026-02-19 17:19:14.879570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb818a08b24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_job_id'), table_name='events')
    op.drop_index(op.f('ix_events_job_uuid'), table_name='events')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('idx_jobs_registry_cal'), table_name='jobs_registry')
    op.drop_index(op.f('idx_jobs_registry_job_date'), table_name='jobs_registry')
    op.drop_table('jobs_registry')
    op.drop_index(op.f('idx_job_registry_date'), table_name='job_registry')
    op.drop_index(op.f('idx_job_registry_status'), table_name='job_registry')
    op.drop_table('job_registry')
    op.drop_index(op.f('idx_jobs_date'), table_name='jobs')
    op.drop_index(op.f('idx_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_client_name'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_external_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('sheet_material_exports')
    op.drop_table('sheet_event_exports')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.create_table('sheet_event_exports',
    sa.Column('event_id', sa.TEXT(), nullable=True),
    sa.Column('exported_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('sheet_material_exports',
    sa.Column('export_key', sa.TEXT(), nullable=True),
    sa.Column('exported_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('export_key')
    )
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('external_job_id', sa.VARCHAR(), nullable=True),
    sa.Column('client_name', sa.VARCHAR(), nullable=False),
    sa.Column('origin_address', sa.VARCHAR(), nullable=True),
    sa.Column('destination_address', sa.VARCHAR(), nullable=True),
    sa.Column('scheduled_start', sa.DATETIME(), nullable=True),
    sa.Column('job_name', sa.TEXT(), nullable=True),
    sa.Column('job_date', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('calendar_event_id', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_external_job_id'), 'jobs', ['external_job_id'], unique=False)
    op.create_index(op.f('ix_jobs_client_name'), 'jobs', ['client_name'], unique=False)
    op.create_index(op.f('idx_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('idx_jobs_date'), 'jobs', ['job_date'], unique=False)
    op.create_table('job_registry',
    sa.Column('job_uuid', sa.TEXT(), nullable=True),
    sa.Column('job_name', sa.TEXT(), nullable=True),
    sa.Column('job_date', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('calendar_event_id', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('job_uuid')
    )
    op.create_index(op.f('idx_job_registry_status'), 'job_registry', ['status'], unique=False)
    op.create_index(op.f('idx_job_registry_date'), 'job_registry', ['job_date'], unique=False)
    op.create_table('jobs_registry',
    sa.Column('job_uuid', sa.TEXT(), nullable=True),
    sa.Column('job_name', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('job_date', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('calendar_event_id', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('job_uuid')
    )
    op.create_index(op.f('idx_jobs_registry_job_date'), 'jobs_registry', ['job_date'], unique=False)
    op.create_index(op.f('idx_jobs_registry_cal'), 'jobs_registry', ['job_date', 'calendar_event_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.VARCHAR(), nullable=False),
    sa.Column('job_uuid', sa.VARCHAR(), nullable=True),
    sa.Column('job_id', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('lat', sa.FLOAT(), nullable=True),
    sa.Column('lng', sa.FLOAT(), nullable=True),
    sa.Column('accuracy_m', sa.FLOAT(), nullable=True),
    sa.Column('note', sa.VARCHAR(), nullable=True),
    sa.Column('synced', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_index(op.f('ix_events_job_uuid'), 'events', ['job_uuid'], unique=False)
    op.create_index(op.f('ix_events_job_id'), 'events', ['job_id'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=1)
    # ### end Alembic commands ###
