"""index events.timestamp

Revision ID: b1e3f5a7c9d2
Revises: a9c2e4f6b8d1
Create Date: 2026-07-15

GET /api/events sorts by timestamp DESC on every history pull, on a table that
only grows. Unindexed, that sort is a full scan that gets slower forever - the
same growing-table / 512 MB worker OOM class the worked-hours indexes addressed.

Written by hand, not autogenerated (alembic/env.py doesn't import every model
module, so --autogenerate emits spurious DROP TABLE ops - see RUNBOOKS).
"""
from typing import Sequence, Union

from alembic import op


revision: str = "b1e3f5a7c9d2"
down_revision: Union[str, Sequence[str], None] = "a9c2e4f6b8d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_index("ix_events_timestamp", "events", ["timestamp"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_events_timestamp", table_name="events")
