"""job report close-out fields: variance, client readiness, scope changes

Revision ID: c4d6e8f0a2b3
Revises: b1e3f5a7c9d2
Create Date: 2026-07-27

Adds five nullable columns to job_reports:

  variance_cause       one cause from a fixed list explaining why the job
                       differed from what was quoted
  variance_note        free text alongside the cause
  client_readiness     how ready the client was on arrival
  client_unready_json  JSON list of what specifically was not ready
  scope_changes_json   JSON list of {kind, hours, note}, one per on-site change

All nullable with no server default and no backfill, on purpose. Every report
submitted before this deploy genuinely has no answer to these questions, and
writing a placeholder would make "not asked" indistinguishable from "crew said
none" the first time anyone charts the causes.

Written by hand, not autogenerated (alembic/env.py doesn't import every model
module, so --autogenerate emits spurious DROP TABLE ops - see RUNBOOKS).
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "c4d6e8f0a2b3"
down_revision: Union[str, Sequence[str], None] = "b1e3f5a7c9d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("job_reports", sa.Column("variance_cause", sa.String(), nullable=True))
    op.add_column("job_reports", sa.Column("variance_note", sa.Text(), nullable=True))
    op.add_column("job_reports", sa.Column("client_readiness", sa.String(), nullable=True))
    op.add_column("job_reports", sa.Column("client_unready_json", sa.Text(), nullable=True))
    op.add_column("job_reports", sa.Column("scope_changes_json", sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column("job_reports", "scope_changes_json")
    op.drop_column("job_reports", "client_unready_json")
    op.drop_column("job_reports", "client_readiness")
    op.drop_column("job_reports", "variance_note")
    op.drop_column("job_reports", "variance_cause")
