"""rename users.is_crew_lead to users.is_skill_rater

Revision ID: c5e7a9b1d3f6
Revises: d4f8b1c6e9a3
Create Date: 2026-07-14

The column never had anything to do with the `crew_lead` role - it is the
admin-set designation for who may rate crew skills, and the Admin roster
already labels its toggle "Skill rater". Now that the crew_lead role no
longer grants skill rating on its own (see ADR 0014), a boolean named
is_crew_lead that is deliberately independent of the crew_lead role is a
trap for the next reader. Rename, don't re-add: ALTER ... RENAME COLUMN
preserves every designation an admin has already made.

Written by hand, not autogenerated (alembic/env.py doesn't import every
model module, so --autogenerate emits spurious DROP TABLE ops).
"""
from typing import Sequence, Union

from alembic import op


revision: str = "c5e7a9b1d3f6"
down_revision: Union[str, Sequence[str], None] = "d4f8b1c6e9a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column("users", "is_crew_lead", new_column_name="is_skill_rater")


def downgrade() -> None:
    op.alter_column("users", "is_skill_rater", new_column_name="is_crew_lead")
