"""Add client-minted item_uuid idempotency keys to estimate + job-inventory items

Estimator items and job-inventory items were the only two offline queues in the
app without an idempotency key. Both endpoints did a plain INSERT against an
autoincrement PK, so the classic flaky-signal failure produced a duplicate row:
the server commits, the response is lost in the tunnel, the client's queue op is
never acked, and the next drain re-POSTs the same item.

Every other queue (events, materials, BOL, RODS, LD-day, incidents, off-job,
office hours, reimbursements) already carried a client uuid and upserted on it.
This brings these two in line. See docs/decisions/0007-client-uuid-idempotency.md.

Nullable + unique: rows written before this migration have no uuid, and Postgres
permits many NULLs under a unique constraint, so only real uuids can collide.
Backfilling the old rows is unnecessary - they are already committed exactly
once, and the client only sends a uuid on new adds.

Written by hand, not autogenerated: alembic/env.py does not import every model
module, so `alembic revision --autogenerate` currently emits spurious DROP TABLE
ops (see docs/RUNBOOKS.md, Known defects).

Revision ID: d4f8b1c6e9a3
Revises: f3b5d7a9c1e2
Create Date: 2026-07-13
"""
from alembic import op
import sqlalchemy as sa

revision = "d4f8b1c6e9a3"
down_revision = "f3b5d7a9c1e2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("estimate_items", sa.Column("item_uuid", sa.String(), nullable=True))
    op.create_index(
        "ix_estimate_items_item_uuid", "estimate_items", ["item_uuid"], unique=True
    )

    op.add_column("job_inventory_items", sa.Column("item_uuid", sa.String(), nullable=True))
    op.create_index(
        "ix_job_inventory_items_item_uuid",
        "job_inventory_items",
        ["item_uuid"],
        unique=True,
    )


def downgrade() -> None:
    op.drop_index("ix_job_inventory_items_item_uuid", table_name="job_inventory_items")
    op.drop_column("job_inventory_items", "item_uuid")

    op.drop_index("ix_estimate_items_item_uuid", table_name="estimate_items")
    op.drop_column("estimate_items", "item_uuid")
