"""job report close-out: variance causes become multi-select

Revision ID: d5e7f9a1b3c4
Revises: c4d6e8f0a2b3
Create Date: 2026-07-28

Adds one nullable column to job_reports:

  variance_causes_json   JSON list of keys from VARIANCE_CAUSES

The singular `variance_cause` column added in c4d6e8f0a2b3 is deliberately left
in place and NOT backfilled. Reports written between 2026-07-27 and this deploy
carry their single cause there; the router reads the JSON column first and falls
back to the string column, so both eras answer the same question without a data
migration over live rows. See ADR 0026.

`scope_changes_json` needs no migration despite its element shape changing
({kind} -> {kinds[], direction}) - it is an opaque Text blob to Postgres, and
ScopeChangeEntry upgrades the old shape on read.

Written by hand, not autogenerated (alembic/env.py doesn't import every model
module, so --autogenerate emits spurious DROP TABLE ops - see RUNBOOKS).
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "d5e7f9a1b3c4"
down_revision: Union[str, Sequence[str], None] = "c4d6e8f0a2b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "job_reports", sa.Column("variance_causes_json", sa.Text(), nullable=True)
    )


def downgrade() -> None:
    op.drop_column("job_reports", "variance_causes_json")
