"""admin payroll corrections (override layer over crew-reported hours)

Revision ID: e6f8a0b2c4d5
Revises: d5e7f9a1b3c4
Create Date: 2026-07-28

Creates payroll_corrections. Each row is an admin's override of one employee's
hours from one source, for one pay period. Nothing here mutates crew-submitted
data - job_reports, off_job_entries and office_hours_entries are untouched, and
the payroll summary applies these on top at read time (ADR 0029).

Indexes: the summary reads corrections by (period_start, period_end) and the
per-employee view by user_id, so both are indexed. The unique constraint on
(period, user, source, source_key, bucket) is what makes an upsert an edit of
an existing correction rather than a second one stacking on top of it.

No FK from source_key to anything: the four correctable sources live in
different tables, one of them has no row identity (a JSON blob inside a job
report), and a correction has to outlive the record it points at.

Written by hand, not autogenerated (alembic/env.py doesn't import every model
module, so --autogenerate emits spurious DROP TABLE ops - see RUNBOOKS).
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "e6f8a0b2c4d5"
down_revision: Union[str, Sequence[str], None] = "d5e7f9a1b3c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "payroll_corrections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.String(), nullable=False),
        sa.Column("period_end", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("source_key", sa.String(), nullable=False, server_default=""),
        sa.Column("source_label", sa.String(), nullable=True),
        sa.Column("work_date", sa.String(), nullable=False),
        sa.Column("bucket", sa.String(length=20), nullable=False, server_default="billable"),
        sa.Column("original_hours", sa.Float(), nullable=False, server_default="0"),
        sa.Column("corrected_hours", sa.Float(), nullable=False, server_default="0"),
        sa.Column("reason", sa.Text(), nullable=False, server_default=""),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_by_name", sa.String(), nullable=True),
        sa.Column("notified_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "period_start",
            "period_end",
            "user_id",
            "source",
            "source_key",
            "bucket",
            name="uq_payroll_correction_target",
        ),
    )
    op.create_index(
        "ix_payroll_corrections_period_start", "payroll_corrections", ["period_start"]
    )
    op.create_index(
        "ix_payroll_corrections_period_end", "payroll_corrections", ["period_end"]
    )
    op.create_index(
        "ix_payroll_corrections_user_id", "payroll_corrections", ["user_id"]
    )
    op.create_index(
        "ix_payroll_corrections_work_date", "payroll_corrections", ["work_date"]
    )


def downgrade() -> None:
    op.drop_index("ix_payroll_corrections_work_date", table_name="payroll_corrections")
    op.drop_index("ix_payroll_corrections_user_id", table_name="payroll_corrections")
    op.drop_index("ix_payroll_corrections_period_end", table_name="payroll_corrections")
    op.drop_index("ix_payroll_corrections_period_start", table_name="payroll_corrections")
    op.drop_table("payroll_corrections")
